---
- name: Which python3
  ansible.builtin.shell:
    cmd: ". ~/.profile && which python3"
  register: which_python_result

- name: Install
  ansible.builtin.shell:
    cmd: ". ~/.profile && pipx install poetry --python {{ which_python_result.stdout }}"