- name: Restart program
  community.general.supervisorctl:
    config: /etc/supervisor/supervisord.conf
    name: "{{ item }}"
    state: restarted
  loop:
    - django-blog-project-celery-worker
    - django-blog-project-celery-beat
    - django-blog-project
  become: yes
  become_method: sudo