# Generated by Django 2.2.5 on 2019-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="scopes",
            field=models.ManyToManyField(to="courses.Course", verbose_name="scopes"),
        ),
    ]
