# Generated by Django 3.2.5 on 2021-07-21 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('alerts', '0002_alert_scopes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['rank', '-created_at'], 'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='created',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='scopes',
        ),
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='modified_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='alert',
            name='show',
            field=models.BooleanField(default=True, verbose_name='show'),
        ),
    ]
