---
- import_tasks: repo.yml
- import_tasks: deps.yml
- import_tasks: envfile.yml
- import_tasks: db.yml
- import_tasks: management.yml
- import_tasks: supervisor.yml
  become: yes
  become_method: sudo
- import_tasks: nginx.yml
  become: yes
  become_method: sudo