---
- name: Ensure static and media directory
  ansible.builtin.file:
    path: /var/www/django-blog-project/blogproject
    state: directory
  become: yes
  become_method: sudo

- name: Run django management commands
  ansible.builtin.shell:
    cmd: ". ~/.profile && poetry run python manage.py {{ item }} --settings=config.settings.production"
    chdir: ~/apps/django-blog-project/
  loop:
    - collectstatic --noinput
    - compilemessages
    - migrate
    - setup_periodic_tasks
