all:
  hosts:
    TencentCloud-CD: &TencentCloud-CD
      ansible_host: 118.24.109.106

    asz: &asz
      ansible_host: 47.106.168.32

  children:
    staging:
      hosts:
        TencentCloud-CD: *TencentCloud-CD

    production:
      hosts:
        asz: *asz
