all:
  hosts:
    TencentCloud-CD: &TencentCloud-CD
      ansible_host: 118.24.109.106

    server_tniifV1S: &server_tniifV1S
      ansible_host: 101.254.176.8

  children:
    staging:
      hosts:
        TencentCloud-CD: *TencentCloud-CD

    production:
      hosts:
        server_tniifV1S: *server_tniifV1S
