# Generated by Django 3.1.1 on 2020-09-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
    ]
