# Generated by Django 3.1.1 on 2020-09-20 08:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('favorites', '0002_auto_20200920_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedItem', to='tags.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedItem', to='tags.Tag', verbose_name='tags'),
        ),
    ]
